import { useMemo, useState } from "react";
import { Bike, BriefcaseBusiness, Check, ClipboardCheck, Download, FileText, UserRound, UsersRound } from "lucide-react";
import jsPDF from "jspdf";
import { PageHeader } from "@/components/page-header";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { timestampSlug } from "@/lib/export";

const initialForm = {
  applicationDate: new Date().toISOString().slice(0, 10), applicationNumber: "", branch: "", fullName: "", firstName: "", middleName: "", lastName: "", dateOfBirth: "", gender: "", maritalStatus: "", nin: "", bvn: "", phone: "", alternatePhone: "", email: "", residentialAddress: "", stateOfOrigin: "", lga: "", occupation: "", employer: "", employerAddress: "", monthlyIncome: "", yearsInWork: "", bikeModel: "", bikeColor: "", bikeRegistration: "", chassisNumber: "", engineNumber: "", cashPrice: "", deposit: "", balance: "", termWeeks: "78", installmentAmount: "", paymentFrequency: "Weekly", nextOfKinName: "", nextOfKinRelationship: "", nextOfKinPhone: "", nextOfKinAddress: "", spouseName: "", spousePhone: "", guarantorName: "", guarantorPhone: "", guarantorAddress: "", referenceOne: "", referenceOnePhone: "", referenceTwo: "", referenceTwoPhone: "", documents: "", notes: "", applicantSignature: "", staffName: "", staffSignature: "",
};

type FormState = typeof initialForm;
type FieldProps = { label: string; name: keyof FormState; form: FormState; update: (name: keyof FormState, value: string) => void; type?: string; required?: boolean; className?: string };

function Field({ label, name, form, update, type = "text", required = false, className = "" }: FieldProps) {
  return <div className={className}><Label htmlFor={name} className="text-xs text-muted-foreground">{label}{required ? " *" : ""}</Label><Input id={name} type={type} value={form[name]} onChange={(event) => update(name, event.target.value)} required={required} className="mt-1.5 bg-background/60" /></div>;
}

function SectionHeading({ title, description, icon }: { title: string; description: string; icon: React.ReactNode }) {
  return <div className="flex items-start gap-3"><div className="rounded-xl bg-primary/10 p-2 text-primary">{icon}</div><div><CardTitle className="text-base">{title}</CardTitle><p className="mt-1 text-xs text-muted-foreground">{description}</p></div></div>;
}

export default function HirePurchaseApplicationPage() {
  const [form, setForm] = useState<FormState>(initialForm);
  const [step, setStep] = useState(0);
  const update = (name: keyof FormState, value: string) => setForm((current) => ({ ...current, [name]: value }));
  const steps = useMemo(() => ["Applicant", "Employment", "Motorcycle & terms", "Contacts", "Declaration"], []);

  const downloadForm = () => {
    const doc = new jsPDF({ unit: "mm", format: "a4" });
    const width = doc.internal.pageSize.getWidth();
    const navy: [number, number, number] = [16, 42, 67];
    const green: [number, number, number] = [15, 157, 117];
    const sections: Array<{ title: string; fields: Array<[string, string]> }> = [
      { title: "Application and applicant", fields: [["Application date", form.applicationDate], ["Application number", form.applicationNumber], ["Branch", form.branch], ["Full name", form.fullName], ["First name", form.firstName], ["Middle name", form.middleName], ["Last name", form.lastName], ["Date of birth", form.dateOfBirth], ["Gender", form.gender], ["Marital status", form.maritalStatus], ["NIN", form.nin], ["BVN", form.bvn], ["Phone", form.phone], ["Alternate phone", form.alternatePhone], ["Email", form.email], ["Residential address", form.residentialAddress], ["State of origin", form.stateOfOrigin], ["LGA", form.lga]] },
      { title: "Employment and business profile", fields: [["Occupation", form.occupation], ["Employer / business", form.employer], ["Employer / business address", form.employerAddress], ["Monthly income", form.monthlyIncome], ["Years in work / business", form.yearsInWork]] },
      { title: "Motorcycle and finance terms", fields: [["Bike model", form.bikeModel], ["Colour", form.bikeColor], ["Registration number", form.bikeRegistration], ["Chassis number", form.chassisNumber], ["Engine number", form.engineNumber], ["Cash price", form.cashPrice], ["Deposit paid", form.deposit], ["Finance balance", form.balance], ["Payment frequency", form.paymentFrequency], ["Repayment term", `${form.termWeeks} weeks`], ["Installment amount", form.installmentAmount]] },
      { title: "Next of kin, spouse and guarantor", fields: [["Next of kin", form.nextOfKinName], ["Next of kin relationship", form.nextOfKinRelationship], ["Next of kin phone", form.nextOfKinPhone], ["Next of kin address", form.nextOfKinAddress], ["Spouse name", form.spouseName], ["Spouse phone", form.spousePhone], ["Guarantor name", form.guarantorName], ["Guarantor phone", form.guarantorPhone], ["Guarantor address", form.guarantorAddress]] },
      { title: "References and document checklist", fields: [["Reference 1", form.referenceOne], ["Reference 1 phone", form.referenceOnePhone], ["Reference 2", form.referenceTwo], ["Reference 2 phone", form.referenceTwoPhone], ["Documents submitted", form.documents]] },
      { title: "Declaration and approval", fields: [["Applicant signature / name", form.applicantSignature], ["Staff name", form.staffName], ["Staff signature", form.staffSignature], ["Notes / declaration", form.notes]] },
    ];
    const valueOrDash = (value: string) => value || "—";
    const drawHeader = () => { doc.setFillColor(...navy); doc.rect(0, 0, width, 30, "F"); doc.setTextColor(255, 255, 255); doc.setFont("helvetica", "bold"); doc.setFontSize(17); doc.text("YamahaPulse", 14, 13); doc.setFontSize(11); doc.text("Hire-Purchase Customer Financing File", width - 14, 13, { align: "right" }); doc.setFont("helvetica", "normal"); doc.setFontSize(8.5); doc.setTextColor(186, 230, 216); doc.text(`Filled form log · ${new Date().toLocaleString()}`, 14, 22); };
    let y = 42;
    drawHeader();
    for (const section of sections) {
      if (y > 250) { doc.addPage(); drawHeader(); y = 42; }
      doc.setFillColor(...green); doc.roundedRect(14, y - 6, width - 28, 9, 2, 2, "F"); doc.setTextColor(255, 255, 255); doc.setFont("helvetica", "bold"); doc.setFontSize(10); doc.text(section.title, 18, y); y += 10;
      doc.setFont("helvetica", "normal"); doc.setFontSize(9);
      for (const [label, value] of section.fields) { const lines = doc.splitTextToSize(valueOrDash(value), width - 68); if (y > 280) { doc.addPage(); drawHeader(); y = 42; } doc.setTextColor(100, 116, 139); doc.text(`${label}:`, 18, y); doc.setTextColor(30, 41, 59); doc.text(lines, 62, y); y += Math.max(8, lines.length * 4); }
      y += 5;
    }
    doc.setFontSize(8); doc.setTextColor(100, 116, 139); doc.text("YamahaPulse · Customer financing record", 14, doc.internal.pageSize.getHeight() - 9); doc.save(`yamaha-hire-purchase-${timestampSlug()}.pdf`);
  };

  const renderStep = () => {
    if (step === 0) return <Card className="border-border bg-card/60"><CardHeader><SectionHeading title="Application and applicant" description="Complete all identity, contact, and banking identification details." icon={<UserRound className="h-4 w-4" />} /></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Field label="Application date" name="applicationDate" form={form} update={update} type="date" required /><Field label="Application number" name="applicationNumber" form={form} update={update} /><Field label="Branch / location" name="branch" form={form} update={update} /><Field label="Full name" name="fullName" form={form} update={update} required className="sm:col-span-2" /><Field label="First name" name="firstName" form={form} update={update} /><Field label="Middle name" name="middleName" form={form} update={update} /><Field label="Last name" name="lastName" form={form} update={update} /><Field label="Date of birth" name="dateOfBirth" form={form} update={update} type="date" /><Field label="Gender" name="gender" form={form} update={update} /><Field label="Marital status" name="maritalStatus" form={form} update={update} /><Field label="NIN" name="nin" form={form} update={update} /><Field label="BVN" name="bvn" form={form} update={update} /><Field label="Phone" name="phone" form={form} update={update} type="tel" required /><Field label="Alternate phone" name="alternatePhone" form={form} update={update} type="tel" /><Field label="Email" name="email" form={form} update={update} type="email" /><Field label="State of origin" name="stateOfOrigin" form={form} update={update} /><Field label="LGA" name="lga" form={form} update={update} /><Field label="Residential address" name="residentialAddress" form={form} update={update} required className="sm:col-span-2 lg:col-span-4" /></CardContent></Card>;
    if (step === 1) return <Card className="border-border bg-card/60"><CardHeader><SectionHeading title="Employment and business profile" description="Capture the customer’s source of income and affordability details." icon={<BriefcaseBusiness className="h-4 w-4" />} /></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2"><Field label="Occupation" name="occupation" form={form} update={update} /><Field label="Employer / business name" name="employer" form={form} update={update} /><Field label="Employer / business address" name="employerAddress" form={form} update={update} className="sm:col-span-2" /><Field label="Monthly income" name="monthlyIncome" form={form} update={update} type="number" /><Field label="Years in work / business" name="yearsInWork" form={form} update={update} type="number" /></CardContent></Card>;
    if (step === 2) return <Card className="border-border bg-card/60"><CardHeader><SectionHeading title="Motorcycle and finance terms" description="The repayment plan is weekly over 78 weeks by default." icon={<Bike className="h-4 w-4" />} /></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Field label="Bike model" name="bikeModel" form={form} update={update} required /><Field label="Colour" name="bikeColor" form={form} update={update} /><Field label="Registration number" name="bikeRegistration" form={form} update={update} /><Field label="Chassis number" name="chassisNumber" form={form} update={update} /><Field label="Engine number" name="engineNumber" form={form} update={update} /><Field label="Cash price" name="cashPrice" form={form} update={update} type="number" required /><Field label="Deposit paid" name="deposit" form={form} update={update} type="number" /><Field label="Finance balance" name="balance" form={form} update={update} type="number" /><Field label="Payment frequency" name="paymentFrequency" form={form} update={update} required /><Field label="Repayment term (weeks)" name="termWeeks" form={form} update={update} type="number" required /><Field label="Weekly installment amount" name="installmentAmount" form={form} update={update} type="number" required /></CardContent></Card>;
    if (step === 3) return <Card className="border-border bg-card/60"><CardHeader><SectionHeading title="Next of kin, spouse, guarantor and references" description="Add all contact and verification details for the financing file." icon={<UsersRound className="h-4 w-4" />} /></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2"><Field label="Next of kin name" name="nextOfKinName" form={form} update={update} /><Field label="Relationship" name="nextOfKinRelationship" form={form} update={update} /><Field label="Next of kin phone" name="nextOfKinPhone" form={form} update={update} type="tel" /><Field label="Next of kin address" name="nextOfKinAddress" form={form} update={update} /><Field label="Spouse name" name="spouseName" form={form} update={update} /><Field label="Spouse phone" name="spousePhone" form={form} update={update} type="tel" /><Field label="Guarantor name" name="guarantorName" form={form} update={update} /><Field label="Guarantor phone" name="guarantorPhone" form={form} update={update} type="tel" /><Field label="Guarantor address" name="guarantorAddress" form={form} update={update} className="sm:col-span-2" /><Field label="Reference 1 name" name="referenceOne" form={form} update={update} /><Field label="Reference 1 phone" name="referenceOnePhone" form={form} update={update} type="tel" /><Field label="Reference 2 name" name="referenceTwo" form={form} update={update} /><Field label="Reference 2 phone" name="referenceTwoPhone" form={form} update={update} type="tel" /></CardContent></Card>;
    return <Card className="border-border bg-card/60"><CardHeader><SectionHeading title="Documents, declaration and approval" description="List supporting documents and complete the sign-off details." icon={<ClipboardCheck className="h-4 w-4" />} /></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2"><div><Label htmlFor="documents" className="text-xs text-muted-foreground">Documents submitted</Label><Textarea id="documents" value={form.documents} onChange={(event) => update("documents", event.target.value)} placeholder="ID, passport photograph, proof of address, bank statement, guarantor documents…" className="mt-1.5 min-h-28 bg-background/60" /></div><div><Label htmlFor="notes" className="text-xs text-muted-foreground">Notes / declaration</Label><Textarea id="notes" value={form.notes} onChange={(event) => update("notes", event.target.value)} className="mt-1.5 min-h-28 bg-background/60" /></div><Field label="Applicant signature / typed name" name="applicantSignature" form={form} update={update} /><Field label="Staff / reviewing officer" name="staffName" form={form} update={update} /><Field label="Staff signature" name="staffSignature" form={form} update={update} /></CardContent></Card>;
  };

  return <div className="space-y-5"><PageHeader title="Hire-Purchase Customer Financing" description="Complete the financing file one section at a time, then download the filled form log." actions={<Badge variant="outline" className="border-primary/30 bg-primary/10 text-primary"><FileText className="mr-2 h-4 w-4" />Weekly · 78 weeks</Badge>} />
    <div className="grid gap-2 sm:grid-cols-5">{steps.map((title, index) => <button type="button" key={title} onClick={() => setStep(index)} className={`rounded-xl border px-3 py-3 text-left text-xs transition-colors ${step === index ? "border-primary/40 bg-primary/10 text-primary" : "border-border bg-card/50 text-muted-foreground"}`}><span className="flex items-center gap-2 font-semibold">{index < step ? <Check className="h-3.5 w-3.5" /> : <span className="flex h-5 w-5 items-center justify-center rounded-full bg-muted text-[10px]">{index + 1}</span>}{title}</span></button>)}</div>
    <form onSubmit={(event) => { event.preventDefault(); if (step < steps.length - 1) setStep((current) => current + 1); else downloadForm(); }} className="space-y-5">{renderStep()}<div className="flex justify-between gap-3"><Button type="button" variant="outline" onClick={() => setStep((current) => Math.max(0, current - 1))} disabled={step === 0}>Previous</Button>{step < steps.length - 1 ? <Button type="submit">Save section & continue</Button> : <Button type="submit" size="lg"><Download className="mr-2 h-4 w-4" />Download filled PDF</Button>}</div></form>
  </div>;
}
