// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://glwinxaanstczuubxqqg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_j2IiuJTttDQd3av6jgy5ig_WLpaOb9P";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);